spring:

  graphql:
    cors:
      allowed-origins:
        - http://localhost:3000
    graphiql:
      enabled: true
    path: /graphql
    websocket:
      path: /graphql

  datasource:
    url: jdbc:mysql://localhost:3307/demo
    username: root
    password: senha-secreta

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: validate | create-drop
      ddl-auto: update

  sql:
    init:
      # never/always
      # always - ca sa imi genereza SQL Tables din Entity
      # always - ca sa imi ruleze SQL Scripts, E.G. data.sql into the DB
      mode: never

logging:
  level:
    org:
      hibernate:
        type: debug
